add jsonpath to handlers
rebelstackio/fluxable pull request #18
Opened 2018-05-15 17:09 UTC by ReinsBrain

closes #17  - this needs some testing during review - i will be adding unit-tests for my next task

2018-05-17 15:18 UTC, jegj commented
i will test it

2018-05-18 16:31 UTC, jegj requested changes

2018-05-18 16:37 UTC, pablolimo commented on lib/store.js
> +				if ( _handlers[action.type].jsonpath ) {
There we will have to get creative with the information provided in the action and put the listener on a top-level component let's say:

storage.dispatch({
type: 'UPDATE_ROW_ENTRY',
id: 'row1',
data: ...
});

Then on the list that holds the row entry do:

storage.on('UPDATE_ROW_ENTRY', (state, action) => {
const { id } = action;
// "UPDATE THE DESIRED ROW ENTRY"
});

2018-05-18 16:44 UTC, jegj commented on lib/store.js
> +				if ( _handlers[action.type].jsonpath ) {
mmm i thought that ... but i think  maybe could be a better solution

2020-08-24 20:38 UTC, oreyes1991 commented
closing this because version 2 doesn't use JSONPath.

2020-08-24 20:38 UTC, closed without merging